-- Modelo de datos para la app de Gestion de Recursos
-- Ejecuta este script en el SQL Editor de Supabase.

create type role_type as enum (
  'administrador',
  'gerente_proyecto',
  'gerente_tarea',
  'lider_integracion',
  'ejecutor'
);

create type project_status as enum ('DECK', 'FROZEN', 'WIP', 'FINALIZADA');
create type alert_type as enum ('retraso_inicio', 'retraso_finalizacion');

create table if not exists lineas_negocio (
  id bigint generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists disciplinas (
  id bigint generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  nombre text not null,
  email text not null unique,
  rol role_type not null
);

create table if not exists proyectos (
  id bigint generated by default as identity primary key,
  title text not null,
  ot text not null unique,
  id_linea_negocio bigint not null references lineas_negocio (id),
  id_gerente_proyecto bigint not null references users (id),
  estado project_status not null default 'DECK',
  fecha_creacion timestamptz not null default now()
);

create table if not exists tareas (
  id bigint generated by default as identity primary key,
  title text not null,
  ot text not null references proyectos (ot) on update cascade on delete cascade,
  id_disciplina bigint not null references disciplinas (id),
  id_gerente_tarea bigint not null references users (id),
  id_ejecutor bigint not null references users (id),
  estado project_status not null default 'DECK',
  f_planeada_inicio_orig date not null,
  f_planeada_fin_orig date not null,
  f_planeada_inicio_act date not null,
  f_planeada_fin_act date not null,
  f_esperada_ini date,
  f_esperada_fin date,
  f_real_inicio timestamptz,
  f_real_fin timestamptz,
  razon_retraso text,
  id_unico_tarea text not null unique,
  fecha_creacion timestamptz not null default now()
);

create table if not exists actividades (
  id bigint generated by default as identity primary key,
  id_unico_tarea text not null references tareas (id_unico_tarea) on update cascade on delete cascade,
  title text not null,
  is_started boolean not null default false,
  is_completed boolean not null default false,
  fecha_inicio timestamptz,
  fecha_finalizacion timestamptz,
  id_tarea_legacy text,
  fecha_creacion timestamptz not null default now(),
  razon_no_cumplimiento text
);

create table if not exists alertas (
  id bigint generated by default as identity primary key,
  tipo alert_type not null,
  id_tarea bigint not null references tareas (id) on delete cascade,
  mensaje text not null,
  activa boolean not null default true
);

create index if not exists idx_proyectos_ot on proyectos (ot);
create index if not exists idx_tareas_ot on tareas (ot);
create index if not exists idx_tareas_id_unico on tareas (id_unico_tarea);
create index if not exists idx_actividades_id_unico on actividades (id_unico_tarea);
create index if not exists idx_alertas_id_tarea on alertas (id_tarea);

insert into lineas_negocio (id, nombre)
values
  (1, 'Aeropuertos'),
  (2, 'Logistica'),
  (3, 'Carton')
on conflict (id) do update set nombre = excluded.nombre;

insert into disciplinas (id, nombre)
values
  (1, 'Software'),
  (2, 'Control'),
  (3, 'Mecanica')
on conflict (id) do update set nombre = excluded.nombre;

insert into users (id, nombre, email, rol)
values
  (1, 'Admin Master', 'admin@recursos.com', 'administrador'),
  (2, 'Juan Proyecto', 'juan@recursos.com', 'gerente_proyecto'),
  (3, 'Ana Tarea', 'ana@recursos.com', 'gerente_tarea'),
  (4, 'Pedro Ejecutor', 'pedro@recursos.com', 'ejecutor')
on conflict (id) do update set
  nombre = excluded.nombre,
  email = excluded.email,
  rol = excluded.rol;

alter table lineas_negocio enable row level security;
alter table disciplinas enable row level security;
alter table users enable row level security;
alter table proyectos enable row level security;
alter table tareas enable row level security;
alter table actividades enable row level security;
alter table alertas enable row level security;

drop policy if exists "lineas_negocio_rw" on lineas_negocio;
drop policy if exists "disciplinas_rw" on disciplinas;
drop policy if exists "users_rw" on users;
drop policy if exists "proyectos_rw" on proyectos;
drop policy if exists "tareas_rw" on tareas;
drop policy if exists "actividades_rw" on actividades;
drop policy if exists "alertas_rw" on alertas;

create policy "lineas_negocio_rw" on lineas_negocio for all using (true) with check (true);
create policy "disciplinas_rw" on disciplinas for all using (true) with check (true);
create policy "users_rw" on users for all using (true) with check (true);
create policy "proyectos_rw" on proyectos for all using (true) with check (true);
create policy "tareas_rw" on tareas for all using (true) with check (true);
create policy "actividades_rw" on actividades for all using (true) with check (true);
create policy "alertas_rw" on alertas for all using (true) with check (true);
